### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by samuelcochard** [trentm/node-ldapauth#25]
Hi, when i try to `npm install ldapauth`, it displays many errors. I spend the last 2 days cheking for a solution but nothing. I tryed to unintall/ reinstall node & npm, same with node-gyp, and still got the error : 

`
> buffertools@1.1.0 install /app/LDAP/node_modules/buffertools
> node-gyp rebuild

  CXX(target) Release/obj.target/buffertools/buffertools.o
../buffertools.cc:19:52: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        Handle<Value> apply(Handle<Object>& buffer, const Arguments& args, HandleScope& scope);
                                                          ^~~~~~~~~
                                                          v8::internal::Arguments
/Users/samuel/.node-gyp/6.9.4/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../buffertools.cc:21:33: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        Handle<Value> operator()(const Arguments& args) {
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/samuel/.node-gyp/6.9.4/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../buffertools.cc:24:28: error: member access into incomplete type 'const v8::internal::Arguments'
                Local<Object> self = args.This();
                                         ^
/Users/samuel/.node-gyp/6.9.4/include/node/v8.h:147:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../buffertools.cc:26:55: error: no member named 'New' in 'v8::String'
                        return ThrowException(Exception::TypeError(String::New(
                                                                   ~~~~~~~~^
../buffertools.cc:35:86: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        Handle<Value> apply(Handle<Object>& buffer, const uint8_t* data, size_t size, const Arguments& args, HandleScope& scope);
                                                                                            ^~~~~~~~~
                                                                                            v8::internal::Arguments
/Users/samuel/.node-gyp/6.9.4/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../buffertools.cc:37:33: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        Handle<Value> operator()(const Arguments& args) {
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/samuel/.node-gyp/6.9.4/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../buffertools.cc:40:28: error: member access into incomplete type 'const v8::internal::Arguments'
                Local<Object> self = args.This();
                                         ^
/Users/samuel/.node-gyp/6.9.4/include/node/v8.h:147:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../buffertools.cc:42:55: error: no member named 'New' in 'v8::String'
                        return ThrowException(Exception::TypeError(String::New(
                                                                   ~~~~~~~~^
../buffertools.cc:46:11: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                if (args[0]->IsString()) {
                    ~~~~^~
../buffertools.cc:47:28: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                        String::Utf8Value s(args[0]->ToString());
                                            ~~~~^~
../buffertools.cc:50:31: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                if (Buffer::HasInstance(args[0])) {
                                        ~~~~^~
../buffertools.cc:51:30: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                        Local<Object> other = args[0]->ToObject();
                                              ~~~~^~
../buffertools.cc:56:88: error: no member named 'New' in 'v8::String'
                static Persistent<String> illegalArgumentException = Persistent<String>::New(String::New(
                                                                                             ~~~~~~~~^
../buffertools.cc:104:52: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        Handle<Value> apply(Handle<Object>& buffer, const Arguments& args, HandleScope& scope) {
                                                          ^~~~~~~~~
                                                          v8::internal::Arguments
/Users/samuel/.node-gyp/6.9.4/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../buffertools.cc:110:52: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        Handle<Value> apply(Handle<Object>& buffer, const Arguments& args, HandleScope& scope) {
                                                          ^~~~~~~~~
                                                          v8::internal::Arguments
/Users/samuel/.node-gyp/6.9.4/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../buffertools.cc:111:11: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                if (args[0]->IsInt32()) {
                    ~~~~^~
../buffertools.cc:112:16: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                        int c = args[0]->ToInt32()->Int32Value();
                                ~~~~^~
../buffertools.cc:116:11: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                if (args[0]->IsString()) {
                    ~~~~^~
../buffertools.cc:117:28: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                        String::Utf8Value s(args[0]->ToString());
                                            ~~~~^~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/buffertools/buffertools.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/LDAP/node_modules/buffertools
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/app/LDAP
└── (empty)

npm WARN enoent ENOENT: no such file or directory, open '/app/LDAP/package.json'
npm WARN LDAP No description
npm WARN LDAP No repository field.
npm WARN LDAP No README data
npm WARN LDAP No license field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ldapauth"
npm ERR! node v6.9.4
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! buffertools@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buffertools@1.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs buffertools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/LDAP/npm-debug.log
`

Haalp ? :)

**Comment by mschmidt712** [comment]
I am seeing the same error on install.

**Comment by mikeatlas** [comment]
Same - this repo appears to be abandoned. @trentm ?

**Comment by mikeatlas** [comment]
https://github.com/vesse/node-ldapauth-fork looks like the self-declared successor.
